"use client";

import React from "react";
import { ImageIcon } from "lucide-react";

import { cn } from "~/lib/classNames";

import { useRatioStore } from "../../store/ratioStore";
import LoadingDots from "./loading-dots";

import "react-medium-image-zoom/dist/styles.css";

import { useMessageStore } from "../../store/messageStore";
import { useMidjourneyStore } from "../../store/midjourneyStore";
import Slider from "../slider/slider";
import { getTwAspectRatio } from "./aspectRatioUtils";

type ImageContainerProps = {
  className?: string;
};

const ImageContainer = ({ className }: ImageContainerProps) => {
  const [messages] = useMessageStore((state) => [state.messages]);
  const [{ isLoading }] = useMidjourneyStore((state) => [state.requestState]);
  const selectedAspectRatio = useRatioStore(
    (state) => state.selectedAspectRatio
  );
  const { value: ratio } = selectedAspectRatio;
  const hasImage = messages.length > 0;
  const aspectRatio = getTwAspectRatio(ratio);

  return (
    <>
      {hasImage ? (
        <Slider />
      ) : (
        <div
          className={cn(
            "flex-center group relative border border-dashed rounded-md lg:h-[500px] mx-auto max-w-full",
            aspectRatio
          )}
        >
          <div className="flex-center h-full max-w-[420px] flex-col text-center">
            {isLoading ? (
              <div className="flex-center flex-col">
                <LoadingDots />
                <p className="my-5 text-sm text-muted-foreground">
                  Your image is currently being generated by Midjourney, please
                  wait a moment.
                </p>
              </div>
            ) : (
              <>
                <ImageIcon className="h-10 w-10 text-muted-foreground" />
                <h3 className="mt-4 text-lg font-semibold">
                  No poster generated
                </h3>
                <p className="mb-4 mt-2 text-sm text-muted-foreground">
                  You have not generate any poster.
                </p>
              </>
            )}
          </div>
        </div>
      )}
    </>
  );
};

export default ImageContainer;
