import type { APIAttachment } from "discord-api-types/v10";
import { create } from "zustand";

import { readStreamData } from "../lib/imageGenerationUtils";

type ImageGenerationState = {
  image: APIAttachment | null;
  isLoading: boolean;
  isImageGenerated: boolean;
  isImageUpscaled: boolean;
  error: string | unknown | null;
  message?: string;
  imageSelected: number | null;
};

type ImageData = APIAttachment & {
  prompt: string;
  messageId: string;
  messageHash: string;
};

export type ImageGenerationSetAction = {
  setImage: (image: APIAttachment | null) => void;
  setIsLoading: (isLoading: boolean) => void;
  setIsImageGenerated: (isImageGenerated: boolean) => void;
  setIsImageUpscaled: (isImageUpscaled: boolean) => void;
  setError: (error: string | unknown | null) => void;
  setImageSelected: (imageSelected: number) => void;
  setMessage: (message: string) => void;
  setClear: () => void;
};

type ImageGenerationAction = ImageGenerationSetAction & {
  generateImage: (prompt: string) => Promise<void>;
  upscaleImage: (index: number | null, image: ImageData) => Promise<void>;
};

export const useImageGenerationStore = create<
  ImageGenerationAction & ImageGenerationState
>()((set) => {
  const setImage = (image: APIAttachment | null) => {
    set(() => ({ image }));
  };
  const setIsLoading = (isLoading: boolean) => {
    set(() => ({ isLoading }));
  };
  const setIsImageGenerated = (isImageGenerated: boolean) => {
    set(() => ({ isImageGenerated }));
  };
  const setIsImageUpscaled = (isImageUpscaled: boolean) => {
    set(() => ({ isImageUpscaled }));
  };
  const setError = (error: string | unknown | null) => {
    set(() => ({ error }));
  };
  const setMessage = (message: string) => {
    set(() => ({ message }));
  };
  const setImageSelected = (index: number) => {
    set(() => ({ imageSelected: index }));
  };
  const setClear = () => {
    set(() => ({
      image: null,
      isLoading: false,
      isImageGenerated: false,
      isImageUpscaled: false,
      error: null,
      message: "",
      imageSelected: null,
    }));
  };

  return {
    image: null,
    isLoading: false,
    isImageGenerated: false,
    isImageUpscaled: false,
    error: null,
    message: "",
    imageSelected: null,
    setImageSelected,
    setImage,
    setIsLoading,
    setIsImageGenerated,
    setIsImageUpscaled,
    setError,
    setMessage,
    setClear,
    generateImage: async (prompt) => {
      setImage(null);
      setIsLoading(true);
      setIsImageGenerated(false);
      setError(null);
      setMessage("");

      try {
        const { status } = await fetch("/api/imagine", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt }),
        });

        if (status === 200) {
          setMessage(
            "Your image is currently being generated by Midjourney, please wait a moment."
          );
          const response = await fetch("/api/get-messages", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ prompt }),
          });

          if (response.body) {
            const reader = response.body.getReader();
            await readStreamData(reader, {
              setImage,
              setIsLoading,
              setIsImageGenerated,
              setError,
              setImageSelected,
              setIsImageUpscaled,
              setMessage,
              setClear,
            });
          }
        } else {
          setMessage(
            `Something went wrong while generating the image, please try again.\n\nStatus code: ${status}`
          );
          throw new Error("Something went wrong");
        }
      } catch (error_: unknown) {
        setMessage(
          `Something went wrong while generating the image, please try again.\n\n${error_}`
        );
        setError(error_);
      }
    },
    upscaleImage: async (index, image) => {
      // setImage(null);
      setIsLoading(true);
      // setIsImageGenerated(false);
      setError(null);
      setMessage("");

      const { prompt, messageId, messageHash } = image;

      try {
        const { status } = await fetch("/api/upscale", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            index,
            messageId,
            messageHash,
          }),
        });

        if (status === 200) {
          setMessage(
            "Your image is currently being generated by Midjourney, please wait a moment."
          );
          const response = await fetch("/api/get-messages", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ prompt, index }),
          });

          if (response.body) {
            const reader = response.body.getReader();
            await readStreamData(reader, {
              setImage,
              setIsLoading,
              setIsImageGenerated,
              setError,
              setImageSelected,
              setIsImageUpscaled,
              setMessage,
              setClear,
            });
          }
        } else {
          setMessage(
            `Something went wrong while upscaling the image, please try again.\n\nStatus code: ${status}`
          );
          throw new Error("Something went wrong");
        }
      } catch (error_: unknown) {
        setMessage(
          `Something went wrong while upscaling the image, please try again.\n\n${error_}`
        );
        setError(error_);
      }
    },
  };
});
