import React from "react";
import { ImageIcon } from "lucide-react";

import { cn } from "~/lib/classNames";

import { useMidjourneyStore } from "../../store/midjourneyStore";
import { useRatioStore } from "../../store/ratioStore";
import { getTwAspectRatio } from "./aspectRatioUtils";
import LoadingDots from "./loading-dots";

type ImageContainerNoPosterProps = {
  size?: "sm" | "md" | "lg";
  className?: string;
};

const ImageContainerNoPoster = ({
  size = "md",
  className,
}: ImageContainerNoPosterProps) => {
  const [{ isLoading }, msg] = useMidjourneyStore((state) => [
    state.requestState,
    state.msg,
  ]);
  const selectedAspectRatio = useRatioStore(
    (state) => state.selectedAspectRatio
  );
  const { value: ratio } = selectedAspectRatio;
  const aspectRatio = getTwAspectRatio(ratio);

  return (
    <div
      id="waiting-poster"
      className={cn(
        "flex-center group relative border border-dashed rounded-md",
        className,
        aspectRatio
      )}
    >
      <div className="flex-center h-full max-w-[420px] flex-col text-center">
        {isLoading ? (
          <div className="flex-center flex-col">
            <span
              className={cn("mb-5 text-muted-foreground", {
                "text-sm": size === "sm",
                "text-base": size === "md",
                "text-lg": size === "lg",
              })}
            >
              {msg}
            </span>
            <LoadingDots />
            <p
              className={cn("my-5 text-muted-foreground", {
                "text-xs": size === "sm",
                "text-sm": size === "md",
                "text-base": size === "lg",
              })}
            >
              Your image is currently being generated by Midjourney, please wait
              a moment.
            </p>
          </div>
        ) : (
          <>
            <ImageIcon className="h-10 w-10 text-muted-foreground" />
            <h3 className="mt-4 text-lg font-semibold">No poster generated</h3>
            <p className="mb-4 mt-2 text-sm text-muted-foreground">
              You have not generate any poster.
            </p>
          </>
        )}
      </div>
    </div>
  );
};

export default ImageContainerNoPoster;
