import React from "react";
import { ImageIcon } from "lucide-react";

import { useImageGenerationStore } from "../store/imageGenerationStore";
import { ImageGrid } from "./ImageGrid";
import LoadingDots from "./LoadingDots";

type ImageContainerProps = {};

const ImageContainer = ({}: ImageContainerProps) => {
  const [
    images,
    imageIndex,
    selectedImage,
    setSelectedImage,
    imageType,
    isLoading,
  ] = useImageGenerationStore((state) => [
    state.images,
    state.imageIndex,
    state.selectedImage,
    state.setSelectedImage,
    state.imageType,
    state.isLoading,
  ]);
  const hasImage = images.length > 0;
  const currentImageUrl = images[imageIndex]?.url;
  const hasImageGrid =
    hasImage && (imageType === "generation" || imageType === "variation");
  return (
    <div className="flex h-[450px] shrink-0 items-center justify-center rounded-md border border-dashed p-4">
      {hasImage ? (
        <div className="relative h-full overflow-hidden">
          {currentImageUrl && (
            <img
              src={currentImageUrl}
              alt=""
              className="h-full min-w-[420px] rounded-md"
            />
          )}
          {hasImageGrid && !isLoading && (
            <ImageGrid
              selectedImage={selectedImage}
              clickHandler={setSelectedImage}
            />
          )}
        </div>
      ) : (
        <div className="mx-auto flex max-w-[420px] flex-col items-center justify-center text-center">
          {isLoading ? (
            <div className="flex-center flex-col">
              <LoadingDots />
              <p className="text-muted-foreground my-5 text-sm">
                Your image is currently being generated by Midjourney, please
                wait a moment.
              </p>
            </div>
          ) : (
            <>
              <ImageIcon className="text-muted-foreground h-10 w-10" />
              <h3 className="mt-4 text-lg font-semibold">
                No poster generated
              </h3>
              <p className="text-muted-foreground mb-4 mt-2 text-sm">
                You have not generate any poster.
              </p>
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default ImageContainer;
