import type { APIAttachment } from "discord-api-types/v10";
import { create } from "zustand";

import { readStreamData } from "../lib/imageGenerationUtils";

export type ImageData = APIAttachment & {
  type?: string;
  prompt: string;
  messageId: string;
  messageHash: string;
  error?: string;
};

type ImageGenerationState = {
  images: ImageData[];
  imageType: "generation" | "upscale" | "variation" | null;
  isLoading: boolean;
  error: string | unknown | null;
  message?: string;
  selectedImage: number | null;
  loadingType: "generation" | "upscale" | "variation" | null;
};

export type ImageGenerationSetAction = {
  addImage: (image: ImageData) => void;
  setImageType: (
    imageType: "generation" | "upscale" | "variation" | null
  ) => void;
  setIsLoading: (isLoading: boolean) => void;
  setError: (error: string | unknown | null) => void;
  setMessage: (message: string) => void;
  setSelectedImage: (imageSelected: number | null) => void;
  setClear: () => void;
  setLoadingType: (
    loadingType: "generation" | "upscale" | "variation" | null
  ) => void;
  undoImage: () => void;
};

type ImageGenerationAction = ImageGenerationSetAction & {
  generateImage: (prompt: string) => Promise<void>;
  upscaleImage: (index: number | null, image: ImageData) => Promise<void>;
  variationImage: (index: number | null, image: ImageData) => Promise<void>;
};

export const useImageGenerationStore = create<
  ImageGenerationAction & ImageGenerationState
>()((set) => {
  const addImage = (image: ImageData) => {
    set((state) => {
      const isGenerated = image.type === "generation_complete";
      const isUpscaled = image.type === "image_upscaled";
      const isVariation = image.type === "variation_complete";
      const isIteration = image.type === "image_iteration";
      const isLoading = image.type === "loading";
      if (isGenerated || isUpscaled || isVariation) {
        const images = [...state.images, image];
        return { images };
      } else if (isIteration) {
        return { images: [image] };
      } else if (isLoading) {
        return { images: [...state.images] };
      } else {
        return { images: [] };
      }
    });
  };
  const setImageType = (
    imageType: "generation" | "upscale" | "variation" | null
  ) => {
    set(() => ({ imageType }));
  };
  const setIsLoading = (isLoading: boolean) => {
    set(() => ({ isLoading }));
  };
  const setError = (error: string | unknown | null) => {
    set(() => ({ error }));
  };
  const setMessage = (message: string) => {
    set(() => ({ message }));
  };
  const setSelectedImage = (index: number | null) => {
    set(() => ({ selectedImage: index }));
  };
  const setClear = () => {
    set(() => ({
      images: [],
      isLoading: false,
      error: null,
      message: "",
      selectedImage: null,
    }));
  };
  const setLoadingType = (
    loadingType: "generation" | "upscale" | "variation" | null
  ) => {
    set(() => ({ loadingType }));
  };
  const undoImage = () => {
    set((state) => {
      const images = [...state.images];
      images.pop();
      return { images };
    });
  };

  const actions = {
    addImage,
    setImageType,
    setIsLoading,
    setError,
    setMessage,
    setSelectedImage,
    setClear,
    setLoadingType,
    undoImage,
  };

  return {
    images: [],
    imageType: null,
    isLoading: false,
    error: null,
    message: "",
    selectedImage: null,
    loadingType: null,
    ...actions,
    generateImage: async (prompt) => {
      setIsLoading(true);
      setError(null);
      setMessage("");
      setLoadingType("generation");

      try {
        const { status } = await fetch("/api/imagine", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt }),
        });

        if (status === 200) {
          setMessage(
            "Your image is currently being generated by Midjourney, please wait a moment."
          );
          const response = await fetch("/api/get-messages", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ prompt }),
          });

          if (response.body) {
            const reader = response.body.getReader();
            await readStreamData(reader, actions);
          }
        } else {
          setMessage(
            `Something went wrong while generating the image, please try again.\n\nStatus code: ${status}`
          );
          throw new Error("Something went wrong");
        }
      } catch (error_: unknown) {
        setMessage(
          `Something went wrong while generating the image, please try again.\n\n${error_}`
        );
        setError(error_);
      }
    },
    upscaleImage: async (index, image) => {
      setIsLoading(true);
      setError(null);
      setMessage("");
      setLoadingType("upscale");
      setSelectedImage(0);

      const { prompt, messageId, messageHash } = image;

      try {
        const { status } = await fetch("/api/upscale", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            index,
            messageId,
            messageHash,
          }),
        });

        if (status === 200) {
          setMessage(
            "Your image is currently being generated by Midjourney, please wait a moment."
          );
          const response = await fetch("/api/get-messages", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ prompt, index, option: "upscale" }),
          });

          if (response.body) {
            const reader = response.body.getReader();
            await readStreamData(reader, actions);
          }
        } else {
          setMessage(
            `Something went wrong while upscaling the image, please try again.\n\nStatus code: ${status}`
          );
          throw new Error("Something went wrong");
        }
      } catch (error_: unknown) {
        setMessage(
          `Something went wrong while upscaling the image, please try again.\n\n${error_}`
        );
        setError(error_);
      }
    },
    variationImage: async (index, image) => {
      setIsLoading(true);
      setError(null);
      setMessage("");
      setLoadingType("variation");
      setSelectedImage(null);

      const { prompt, messageId, messageHash } = image;

      try {
        const { status } = await fetch("/api/variation", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            index,
            messageId,
            messageHash,
          }),
        });

        if (status === 200) {
          setMessage(
            "Your image is currently being generated by Midjourney, please wait a moment."
          );
          const response = await fetch("/api/get-messages", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ prompt, index, option: "variation" }),
          });

          if (response.body) {
            const reader = response.body.getReader();
            await readStreamData(reader, actions);
          }
        } else {
          setMessage(
            `Something went wrong while upscaling the image, please try again.\n\nStatus code: ${status}`
          );
          throw new Error("Something went wrong");
        }
      } catch (error_: unknown) {
        setMessage(
          `Something went wrong while upscaling the image, please try again.\n\n${error_}`
        );
        setError(error_);
      }
    },
  };
});
